# 需求：
#  监听 8080 端口
#  / 开头的请求 → 返回 static 目录的静态文件
#  /api/ 开头的请求 → 反向代理到 http://api:50051
#  对 /api/ 限流：每秒 5 个请求，burst 5
#  添加 proxy_set_header 传递真实 IP
#  自定义 access_log 格式，记录响应时间

# TODO: 补充 http 块
# TODO: 定义 limit_req_zone
# TODO: 配置 server 块

http {
    # 日志格式,加入 $request_id 和 $upstream_response_time 变量
    log_format main '$remote_addr - [$time_local] "$request" '
                    'status: $status | req_id: $request_id | upstream_time: $upstream_response_time'; 

    # 限流定义（全局）
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=5r/s;

    server {
        listen 8080;

        # 定义访问日志
        access_log /var/log/nginx/access.log main;

        # 静态文件
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # 反向代理
        location /api/ {
            proxy_pass http://api:50051;

            # 传递真实 IP
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # 将唯一ID传递给后端API
            proxy_set_header X-Request-Id $request_id;

            # 将唯一ID返回给前端客户端
            add_header X-Request-Id $request_id;
            
            # 限流
            limit_req zone=mylimit burst=5;
        }
    }
}